How to define variables? Simple!

In [1]:
a = 1
b = 23.345
δ = 7
Črt = "Črt"
; #newline 

#= this is a 
multiline 
comment
=#


Strings and printing.

In [2]:
greet = "Hello"
whom = "world"
message = "$greet, $whom.\n" #inserts into string (called interoplation)

print(Črt)
print(b)
print("\n")
print(message)
print("\n")


Črt23.345
Hello, world.



Types are important!

In [3]:
typeof(a)

Int64

In [4]:
typeof(b)

Float64

In [5]:
typeof(pi)

Irrational{:π}

In [6]:
BigFloat(1) + pi

4.141592653589793238462643383279502884197169399375105820974944592307816406286198

In [7]:
BigFloat(1) + Float64(pi)

4.141592653589793115997963468544185161590576171875

Important tip: ensure the types of the variables are not changed during execution!
This is called "type stability".

In [8]:
a = 1.0 #this is bad for performance because we changed the type of a
typeof(a)

Float64

Functions help with code reusability and performance. Also global variables are bad in julia because compiler cannot optimize as well. 

In [9]:
function f(x)
    x^2 + 1    
end #ends the function and returns last computation

f(2)

5

In [10]:
#quick definition
g(x) = sin(x)

#anonymous functions stored in variable
h = (x, y) -> g(x) + y

h(3.5, 1.0)

0.6492167723103801

In [11]:
#positional, default and keyword arguments
function wave(x, y=1.0 ; a=1.0) #kwargs following ; generally worse performance
    return a*cos(x) + y
end

wave(0.1)

1.9950041652780257

In [12]:
function variable_arguments(x, args...) #might cause performance issues ... is called splating
    print("I accept everything!")
end

variable_arguments(1, 2,  5, 6)

I accept everything!

In [13]:
function modify!(x) #convention: function that modifies its argument name ends with !
    x + 1
end

x = 1
modify!(x)

2

Flow control, loops...

In [14]:
function absolute(x)
    if x >= 0
        return x
    else
        return -x
    end
end

function while_test()
    i=0
    while(i<30)
        println(i)
        i += 1
    end
end

for i in 1:100 #ranges 
    if i>10
        break
    else
   	    println(i^2) #printline 
    end
end


1
4
9
16
25
36
49
64
81
100


Usefull data structures: arrays, vectors and tuples

In [15]:
v = [1,2,3]
A = [1 2 3 ; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [16]:
A * v

2-element Vector{Int64}:
 14
 32

Multidimensional arrays. Be careful to iterate in the right way! column-major storage, like fortran not like python. 

In [17]:
table = zeros(2,3,4)
for k in 1:4
    for j in 1:3
        for i in 1:2
            table[i,j,k] = i*j*k
        end
    end
end

table

2×3×4 Array{Float64, 3}:
[:, :, 1] =
 1.0  2.0  3.0
 2.0  4.0  6.0

[:, :, 2] =
 2.0  4.0   6.0
 4.0  8.0  12.0

[:, :, 3] =
 3.0   6.0   9.0
 6.0  12.0  18.0

[:, :, 4] =
 4.0   8.0  12.0
 8.0  16.0  24.0

In [18]:
table[:, 1:3, 1:2]

2×3×2 Array{Float64, 3}:
[:, :, 1] =
 1.0  2.0  3.0
 2.0  4.0  6.0

[:, :, 2] =
 2.0  4.0   6.0
 4.0  8.0  12.0

In [19]:
for n in eachindex(table) #most efficient way of looping through array
    print(n)
    print(" ")
    print(table[n])
    print("\n")
end    

1 1.0
2 2.0
3 2.0
4 4.0
5 3.0
6 6.0
7 2.0
8 4.0
9 4.0
10 8.0
11 6.0
12 12.0
13 3.0
14 6.0
15 6.0
16 12.0
17 9.0
18 18.0
19 4.0
20 8.0
21 8.0
22 16.0
23 12.0
24 24.0


In [20]:
#brodcasting is done with . Similar to numpy functions

a = [1,2,3]
sin.(a)


3-element Vector{Float64}:
 0.8414709848078965
 0.9092974268256817
 0.1411200080598672

In [21]:
tuple1 = (1, 2, 3) #tuples are immutable like in python
a, b, c = tuple1

function splat_test(a, b, c)
    return a*b*c
end

splat_test(tuple1...)

6

Custom types

In [1]:
abstract type Being
end

struct Physicist <: Being
    name::String
    subject::String
end

#default constructor


In [3]:
crt = Physicist("Črt", "Quantum Chaos")
matt = Physicist("Matt", "Rydberg Atoms")
matt.subject 

"Rydberg Atoms"

In [24]:
matt.subject = "Quantum Chaos"

LoadError: setfield!: immutable struct of type Physicist cannot be changed

In [6]:
mutable struct Droid <: Being
    name::String
    subject::String
end



In [8]:
r2 = Droid("R2-D2", "Mechanical Engineering")
threepo = Droid("C3-PO", "Protocol")

Droid("C3-PO", "Protocol")

In [9]:
r2.subject = "Gastronomy"

"Gastronomy"

Multiple Dispatch

In [10]:
function introduce(me::Being)
    println("I am $(me.name) and I like $(me.subject).")
end

introduce (generic function with 1 method)

In [12]:
introduce(threepo)
introduce(crt)

I am C3-PO and I like Protocol.
I am Črt and I like Quantum Chaos.


In [ ]:
introduce(1)

In [15]:
function introduce(me::Number)
    println("I am $me and I am a $(typeof(me)).")
end

function introduce(me::Integer)
    println("I am $me and I am an $(typeof(me)).")
end

introduce (generic function with 3 methods)

In [17]:
introduce(1)
introduce(1.0)

I am 1 and I am an Int64.
I am 1.0 and I am a Float64.


In [8]:
struct Cat <: Being
    name::String
    subject::String

end

Cat(name)= Cat(name, "Sleeping")


Cat

In [9]:
miho = Cat("Mihovil")

Cat("Mihovil", "Sleeping")

In [10]:
blixa = Cat("Blixa", "Eating")

Cat("Blixa", "Eating")

In [3]:
struct Plant <: Being
    name::String
    subject::String
    Plant(name) = new(name, "Growing")
end

In [4]:
beni = Plant("Ficus")

Plant("Ficus", "Growing")

In [5]:
mon = Plant("Monstera", "Dying")

LoadError: MethodError: no method matching Plant(::String, ::String)
Closest candidates are:
  Plant(::Any) at In[3]:4

Parametric types and functions